# A simple CRUD application for files and folders
# with folder navigation
# generated by ChatGPT and modified by me

import os

def list_items():
    print(f"\n Current Directory: {os.getcwd()}")
    items = os.listdir()
    if not items:
        print(" Empty Folder")
    else:
        for i, item in enumerate(items):
            print(f"{i+1}. {item}")

def change_directory():
    folder = input("Enter folder name to enter: ")
    if os.path.isdir(folder):
        os.chdir(folder)
        print(f" Entered folder: {os.getcwd()}")
    else:
        print(" Folder not found.")

def create_file():
    name = input("Enter file name: ")
    with open(name, 'w') as f:
        f.write(input("Enter content: "))
    print(" File created.")

def create_folder():
    name = input("Enter folder name: ")
    os.mkdir(name)
    print(" Folder created.")

def read_file():
    name = input("Enter file name: ")
    if os.path.exists(name) and os.path.isfile(name):
        with open(name, 'r') as f:
            print(" Content:\n" + f.read())
    else:
        print(" File not found.")

def update_file():
    name = input("Enter file name: ")
    if os.path.exists(name) and os.path.isfile(name):
        with open(name, 'a') as f:
            f.write("\n" + input("Enter content to append: "))
        print(" File updated.")
    else:
        print(" File not found.")

def delete_file():
    name = input("Enter file name: ")
    if os.path.exists(name) and os.path.isfile(name):
        os.remove(name)
        print(" File deleted.")
    else:
        print(" File not found.")

def delete_folder():
    name = input("Enter folder name: ")
    if os.path.exists(name) and os.path.isdir(name):
        try:
            os.rmdir(name)  # only works for empty folders
            print(" Folder deleted.")
        except:
            print(" Folder not empty.")
    else:
        print(" Folder not found.")

def go_back():
    os.chdir("..")
    print(f"↩ Moved to: {os.getcwd()}")

def menu():
    while True:
        print("\n CRUD File/Folder App with Navigation")
        print("1. List Items")
        print("2. Change Directory (Enter Folder)")
        print("3. Go Back to Previous Folder")
        print("4. Create File")
        print("5. Create Folder")
        print("6. Read File")
        print("7. Update File")
        print("8. Delete File")
        print("9. Delete Folder")
        print("0. Exit")
        choice = input("Select option: ")
        if choice == '1':
            list_items()
        elif choice == '2':
            change_directory()
        elif choice == '3':
            go_back()
        elif choice == '4':
            create_file()
        elif choice == '5':
            create_folder()
        elif choice == '6':
            read_file()
        elif choice == '7':
            update_file()
        elif choice == '8':
            delete_file()
        elif choice == '9':
            delete_folder()
        elif choice == '0':
            print(" Exiting...")
            break
        else:
            print(" Invalid choice.")

if __name__ == "__main__":
    menu()
